<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_false_EST-1</name>
   <tag></tag>
   <elementGuidId>c940d854-6866-4a74-8893-5c7d3643cc3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='EST-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;EST-1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;EST-1&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>665e7e29-36f4-4e68-baf4-dcbef28188d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>0dccfec9-3fc3-4264-9ae5-475154b09a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EST-1</value>
      <webElementGuid>64cf7ecf-6534-42b4-8c52-d72bf52c4f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e1ed0775-683d-4cbc-b56a-b895a65de7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b0747008-df0d-466c-8cb4-42816d50a720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Cart&quot;)/form[1]/table[1]/tbody[1]/tr[2]/td[5]/input[1]</value>
      <webElementGuid>3ca77921-b5da-41b4-8a85-06c83bdb5d92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='EST-1']</value>
      <webElementGuid>c9223f6b-69e8-4126-803a-a088f4f2a73b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cart']/form/table/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>8b53dcf0-05dd-4645-90a2-9535bf731b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>1e1c0f91-b4bb-4715-9f38-eee8f346b62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'EST-1' and @type = 'text']</value>
      <webElementGuid>4d3c8575-f885-49a9-8bd3-7f653efdfb9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
