<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>0ad96dc6-86d9-46b6-8958-b7b01103af81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MainImageContent > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MainImageContent']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#MainImageContent >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f0bf30e6-1e35-45d9-aef0-c5ece7c4f21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>355</value>
      <webElementGuid>83c5e84e-ecd4-43f8-b863-708ef9854f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/splash.gif</value>
      <webElementGuid>587ba50d-202d-4d8c-8025-f60a3e2d7879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>8094dc60-e088-49bd-a969-dcea82826d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>usemap</name>
      <type>Main</type>
      <value>#estoremap</value>
      <webElementGuid>2957eb1a-6c3a-469e-8273-313054cfc883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>350</value>
      <webElementGuid>1906fe38-862d-48a5-8539-277c77c23bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainImageContent&quot;)/img[1]</value>
      <webElementGuid>cff33685-0f54-403e-9da2-7e8d0b5dfca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MainImageContent']/img</value>
      <webElementGuid>25a0cdcf-f28e-40a7-9d6b-4ff2d7122f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/img</value>
      <webElementGuid>9ae8bdb2-9e64-4023-b2ee-2931ac80c334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/splash.gif']</value>
      <webElementGuid>74278854-e339-4797-b01c-3ae9f6c610b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
